// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'celebrity';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String BANNER_HOME = 'assets/clip_path/banner_home.png';
  static const String CARD1 = 'assets/clip_path/card1.png';
  static const String CARD2 = 'assets/clip_path/card2.png';
  static const String CARD3 = 'assets/clip_path/card3.png';
  static const String CARD4 = 'assets/clip_path/card4.png';
  static const String PERSONAL_MEET = 'assets/clip_path/personal_meet.png';
  static const String VIDEO_CALL = 'assets/clip_path/video_call.png';
  static const String VIDEOS_BITES = 'assets/clip_path/videos_bites.png';
  static const String CO = 'assets/icons/co.png';
  static const String CONGRATULATIONIMG = 'assets/icons/congratulationImg.png';
  static const String GOOGLE = 'assets/icons/google.png';
  static const String NOTIFICATION = 'assets/icons/notification.svg';
  static const String PAYPAL = 'assets/icons/paypal.png';
  static const String RIGHT = 'assets/icons/right.png';
  static const String SUBTRACT = 'assets/images/Subtract.png';
  static const String ALLU = 'assets/images/allu.png';
  static const String BGG = 'assets/images/bgg.png';
  static const String CALL = 'assets/images/call.png';
  static const String CALLINGIMG = 'assets/images/callingImg.png';
  static const String FANCARD = 'assets/images/fancard.png';
  static const String FANCARD1 = 'assets/images/fancard1.png';
  static const String FANCARD2 = 'assets/images/fancard2.png';
  static const String GRID = 'assets/images/grid.png';
  static const String IMAGEMAN = 'assets/images/imageMan.png';
  static const String KARTHIKEYA = 'assets/images/karthikeya.png';
  static const String KRITI = 'assets/images/kriti.png';
  static const String MANSIMG = 'assets/images/mansimg.png';
  static const String ONBG = 'assets/images/onBg.png';
  static const String ONBOARMANS = 'assets/images/onboarMans.png';
  static const String ONBOARD = 'assets/images/onboard.png';
  static const String PAYMENT_SUCCESS = 'assets/images/payment_success.png';
  static const String PERSONAL_MEET1 = 'assets/images/personal_meet1.png';
  static const String PERSONAL_MEET2 = 'assets/images/personal_meet2.png';
  static const String PROFILE = 'assets/images/profile.png';
  static const String RAMA = 'assets/images/rama.png';
  static const String SAMANTHA = 'assets/images/samantha.png';
  static const String SINGERS = 'assets/images/singers.png';
  static const String SOON = 'assets/images/soon.png';
  static const String THANK = 'assets/images/thank.png';
  static const String THANKYOU = 'assets/images/thankYou.png';
  static const String PP = 'assets/logo/pp.png';
}
